id: P009165
initial_creation_type: ocr
source_metadata:
  id: bdr:W23896
  title: ཨ་ཕྱི་ཆོས་ཀྱི་སྒྲོལ་མའི་ཤོ་མོ་སྣང་སྲིད་གསལ་བའི་མེ་ལོང
  author: ''
  volumes:
    61ac22e48a9e4e69a85ab58e6d69737c:
      image_group_id: I3176
      title: ''
      volume_number: 1
      total_pages: 186
