id: I9BAC4B4E
legacy_id: P009165
ocr_import_info:
  bdrc_scan_id: W23896
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T14:38:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:01:11.872908+00:00'
last_modified: 2022-09-02 13:01:20.797695
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23896
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23896
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཨ་ཕྱི་ཆོས་ཀྱི་སྒྲོལ་མའི་ཤོ་མོ་སྣང་སྲིད་གསལ་བའི་མེ་ལོང་།
  author: འབྲི་གུང་ཆེ་ཚང ༠༢་དཀོན་མཆོག་འཕྲིན་ལས་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8572257459256829
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I3176:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3176
      total_pages: 186
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3176.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8572257459256829
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
